import type { DesktopHomeProps } from './home';
import { Icon } from '@/components/ui/icon';
import { WebLink } from '@/components/web/shell.web';

export function DesktopHome(p: DesktopHomeProps) {
  return <div className="atlas-dashboard"><div className="atlas-page-heading"><div><span className="atlas-eyebrow">YOUR MONEY, AT A GLANCE</span><h1>Hello, {p.greeting}<span className="atlas-pink">.</span></h1><p>Here&apos;s your world of money today.</p></div><button className="atlas-btn atlas-btn-quiet" onClick={p.onRefresh} disabled={p.refreshing}><Icon name="refresh-outline" size={17} color="textSecondary" />{p.refreshing ? 'Refreshing…' : 'Refresh'}</button></div>
    <div className="atlas-dashboard-grid"><div className="atlas-dashboard-primary"><div className="atlas-home-balance">{p.hero}</div>{p.pending}<section className="atlas-quick-actions"><button onClick={p.onDeposit}><span className="atlas-quick-icon"><Icon name="add-outline" size={22} color="accentPinkTint" /></span><span><strong>Add money</strong><small>Top up your balance</small></span><Icon name="arrow-forward" size={16} color="textSecondary" /></button><WebLink href="/send"><span className="atlas-quick-icon"><Icon name="paper-plane-outline" size={21} color="accentPinkTint" /></span><span><strong>Send money</strong><small>Friends, links & banks</small></span><Icon name="arrow-forward" size={16} color="textSecondary" /></WebLink><WebLink href="/trade"><span className="atlas-quick-icon"><Icon name="trending-up-outline" size={21} color="accentPinkTint" /></span><span><strong>Explore markets</strong><small>Find your next move</small></span><Icon name="arrow-forward" size={16} color="textSecondary" /></WebLink></section><div className="atlas-desktop-assets">{p.assets}</div><section className="atlas-desktop-activity">{p.activity}</section></div>
    <aside className="atlas-dashboard-rail" aria-label="More from Atlas">{p.earn}<div className="atlas-discover-card"><span className="atlas-eyebrow">MAKE YOUR NEXT MOVE</span><h2>A world beyond<br />your balance.</h2><p>Find something worth owning.</p><div className="atlas-discover-links"><WebLink href="/trade"><Icon name="trending-up-outline" size={20} color="accentPinkTint" /><span>Stocks, crypto & memes</span><Icon name="arrow-forward" size={16} color="textSecondary" /></WebLink><WebLink href="/perps"><Icon name="pulse-outline" size={20} color="accentPinkTint" /><span>Go long or short</span><Icon name="arrow-forward" size={16} color="textSecondary" /></WebLink><WebLink href="/more"><Icon name="grid-outline" size={20} color="accentPinkTint" /><span>Apps & more</span><Icon name="arrow-forward" size={16} color="textSecondary" /></WebLink></div></div>{p.nextSteps}{p.promo}</aside></div>
  </div>;
}
