import { useAtlasAuth } from '@/auth/context';
import { Icon } from '@/components/ui/icon';
import { PillButton } from '@/components/ui/pill-button';
import { AtlasWordmark, WebLink } from '@/components/web/shell.web';

export function DesktopWelcome() {
  const { ready, loginWithGoogle, googleLoading, googleError } = useAtlasAuth();
  return <div className="atlas-welcome">
    <section className="atlas-welcome-hero">
      <div className="atlas-welcome-copy"><div className="atlas-eyebrow"><span />ONE BALANCE. ENDLESS POSSIBILITIES.</div><h1>Your money.<br />Your world.<br /><em>Your move.</em></h1><p>From your first deposit to your next big idea. Send money, explore stocks, crypto and predictions, and put your cash to work—all with Atlas.</p><div className="atlas-feature-pills"><span>Stocks</span><span>Memes & crypto</span><span>Savings</span><span>Predictions</span><span>Payments</span></div><WebLink href="/install" className="atlas-welcome-download"><Icon name="phone-portrait-outline" size={18} color="accentPinkTint" /><span>Made for your pocket, too.</span><strong>Get Atlas <span aria-hidden="true">↗</span></strong></WebLink></div>
      <div className="atlas-welcome-right"><div className="atlas-orbit-art" aria-hidden="true"><div className="atlas-orbit atlas-orbit-one" /><div className="atlas-orbit atlas-orbit-two" /><div className="atlas-orbit atlas-orbit-three" /><img className="atlas-orbit-core" src="/atlas-icon.png" alt="" /><span className="atlas-orbit-token token-predictions"><Icon name="stats-chart-outline" color="accentPinkTint" size={20} />Predictions</span><span className="atlas-orbit-token token-sol"><Icon name="planet-outline" color="accentPinkTint" size={20} />SOL</span><span className="atlas-orbit-token token-stocks"><Icon name="trending-up-outline" color="accentPinkTint" size={20} />Stocks</span><span className="atlas-orbit-token token-naira">₦<span>Your balance</span></span><span className="atlas-orbit-token token-memes"><Icon name="flame-outline" color="accentPinkTint" size={20} />Memes</span></div>
      <div className="atlas-login-card" id="atlas-login"><span className="atlas-eyebrow">LET&apos;S GET YOU STARTED</span><h2>Welcome to Atlas.</h2><p>A whole world of money, with one simple login.</p><div className="atlas-login-actions"><PillButton label="Continue with Google" icon="logo-google" disabled={!ready} loading={googleLoading} onPress={loginWithGoogle} /><WebLink href="/sign-in-email" className="atlas-btn atlas-btn-email"><Icon name="mail-outline" size={18} />Continue with email</WebLink></div>{googleError && <p className="atlas-auth-error" role="alert">{googleError}</p>}<div className="atlas-login-note"><Icon name="shield-checkmark-outline" size={17} color="textSecondary" /><span>No seed phrase. Your wallet is set up for you.</span></div></div></div>
    </section>
    <section className="atlas-feature-section" id="atlas-features"><div className="atlas-section-intro"><span className="atlas-eyebrow">A LITTLE LESS FRICTION</span><h2>More life. More possibilities.</h2><p>Everything you need to make your next money move.</p></div><div className="atlas-feature-grid">
      {[{icon:'cash-outline' as const, title:'Start with naira', copy:'Add money from your bank or a wallet. Keep track of it in the currency you know.'}, {icon:'trending-up-outline' as const, title:'Find your next favourite', copy:'Explore stocks, crypto and memes. See the price and fees before you buy.'}, {icon:'leaf-outline' as const, title:'Give your cash a purpose', copy:'Explore savings opportunities and manage them alongside your assets.'}, {icon:'paper-plane-outline' as const, title:'Send it your way', copy:'Pay an Atlas friend, create a cash link, or cash out to your bank.'}].map((f,i)=><article key={f.title} className="atlas-feature-card"><span className="atlas-feature-number">0{i+1}</span><span className="atlas-feature-icon"><Icon name={f.icon} size={26} color="accentPinkTint" /></span><h3>{f.title}</h3><p>{f.copy}</p></article>)}
    </div></section>
    <section className="atlas-bottom-cta"><div><span className="atlas-eyebrow">BIG SCREEN. SMALL SCREEN. YOUR ATLAS.</span><h2>Good money moves travel.</h2><p>Get Atlas on Android, or add it to your iPhone Home Screen.</p></div><WebLink href="/install" className="atlas-btn atlas-btn-pink">Get Atlas <Icon name="arrow-forward" size={18} /></WebLink></section>
    <footer className="atlas-footer"><AtlasWordmark /><span>One balance. Your world.</span><WebLink href="/install">Get the app ↗</WebLink></footer>
  </div>;
}
