import { useState } from 'react';
import { useAtlasAuth } from '@/auth/context';
import { Icon } from '@/components/ui/icon';
import { AtlasWordmark, WebLink } from '@/components/web/shell.web';
import { androidApkUrl } from '@/web/install';
import { useBrowserDevice } from '@/web/use-desktop';

const IPHONE = [
  {title:'Open Atlas in Safari', text:'Open this website in Safari on your iPhone. If you came from another app, open the link in Safari first.', icon:'compass-outline' as const},
  {title:'Tap Share', text:'Tap the Share icon. If it is hidden, open the ••• menu first, then choose Share.', icon:'share-outline' as const},
  {title:'Add to Home Screen', text:'Choose Add to Home Screen. Scroll down, or tap Edit Actions if you do not see it.', icon:'add-circle-outline' as const},
  {title:'Make it yours', text:'Keep the name Atlas and leave Open as Web App switched on if shown. Tap Add, then open Atlas from your Home Screen.', icon:'checkmark-circle-outline' as const},
];
export default function InstallScreen() {
  const { authenticated } = useAtlasAuth();
  const device = useBrowserDevice();
  const [choice, setPlatform] = useState<'ios' | 'android' | null>(null);
  const platform = choice ?? (device === 'android' ? 'android' : 'ios');
  return <div className="atlas-install-page"><WebLink href={authenticated ? '/' : '/sign-in'} className="atlas-install-back"><Icon name="arrow-back" size={17} color="textSecondary" />Back to Atlas</WebLink><div className="atlas-install-heading"><span className="atlas-eyebrow">YOUR ATLAS. IN YOUR POCKET.</span><h1>Take your world<br /><em>with you.</em></h1><p>On a computer? Atlas works right here in your browser.<br className="atlas-desktop-break" /> On your phone, choose how to get started.</p></div><div className="atlas-platform-tabs" role="tablist" aria-label="Choose your phone"><button id="tab-ios" role="tab" aria-selected={platform === 'ios'} aria-controls="install-ios" onClick={()=>setPlatform('ios')}><Icon name="logo-apple" size={18} color={platform === 'ios' ? 'textPrimary' : 'textSecondary'} />iPhone</button><button id="tab-android" role="tab" aria-selected={platform === 'android'} aria-controls="install-android" onClick={()=>setPlatform('android')}><Icon name="logo-android" size={18} color={platform === 'android' ? 'textPrimary' : 'textSecondary'} />Android</button></div>
    {platform === 'ios' ? <section id="install-ios" role="tabpanel" aria-labelledby="tab-ios"><div className="atlas-install-notice"><Icon name="information-circle-outline" size={21} color="accentPinkTint" /><span>Use Atlas as a web app on your iPhone. There is no iPhone app download from this website.</span></div><div className="atlas-install-steps">{IPHONE.map((s,i)=><article key={s.title} className="atlas-install-step"><div className={`atlas-phone-art phone-step-${i}`} aria-hidden="true"><div className="atlas-phone-speaker" /><div className="atlas-phone-top"><AtlasWordmark /></div>{i === 0 ? <div className="atlas-phone-welcome"><span className="atlas-phone-orb">a</span><strong>Your money.<br />Your world.</strong><span className="atlas-phone-pill">Continue with Google</span></div> : i === 1 ? <div className="atlas-phone-menu"><span>Share</span><div className="atlas-share-art"><Icon name="share-outline" size={35} color="accentPinkTint" /></div><span className="atlas-highlight-row">Share website ↗</span></div> : i === 2 ? <div className="atlas-phone-menu"><span>Options</span><small>Copy link</small><small>Add to favourites</small><span className="atlas-highlight-row">⊕ Add to Home Screen</span></div> : <div className="atlas-phone-menu"><span className="atlas-phone-app-icon">a</span><strong>Atlas</strong><small>Open as Web App ✓</small><span className="atlas-phone-pill">Add</span></div>}<div className="atlas-phone-home-line" /></div><div className="atlas-step-title"><span>{i+1}</span><h2>{s.title}</h2></div><p>{s.text}</p></article>)}</div><p className="atlas-install-footnote">Sign in when you open it. Your account and balance are the same on every device.</p></section> : <section id="install-android" role="tabpanel" aria-labelledby="tab-android" className="atlas-android-panel"><div className="atlas-android-art" aria-hidden="true"><span className="atlas-android-orbit" /><span className="atlas-android-logo"><Icon name="logo-android" size={72} /></span></div><div><span className="atlas-eyebrow">ATLAS FOR ANDROID</span><h2>Your money moves<br />with you.</h2><p>Download the Atlas APK, open the file and follow Android&apos;s installation prompts. Allow installation from your browser only when Android asks.</p>{androidApkUrl ? <a className="atlas-btn atlas-btn-pink" href={androidApkUrl} download rel="noopener noreferrer"><Icon name="download-outline" size={18} />Download Atlas for Android</a> : <><button className="atlas-btn atlas-btn-pink" disabled><Icon name="download-outline" size={18} />Android download coming soon</button><p className="atlas-install-footnote" role="status">The APK is not published yet. You can use Atlas in your browser today.</p></>}<WebLink className="atlas-text-link" href={authenticated ? '/' : '/sign-in'}>Continue in your browser <span aria-hidden="true">↗</span></WebLink></div></section>}
  </div>;
}
